---
abstract: 'Make clean html snippets from POD'
author:
  - 'Daisuke Murase C<typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-HTMLEmbed
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.10
  Carp::Clan: 0
  HTML::Entities: 0
  HTML::TreeBuilder: 0
  List::Util: 0
  Pod::Simple::Search: 0
  Pod::Simple::XHTML: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/Pod-HTMLEmbed.git
version: 0.02
